services:

  database:
    image: postgres:18-trixie
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports: 
      - "${POSTGRES_PORT}:5432"
    command: ["postgres", "-N", "1000"]
