name: ServerSide Builder

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  python-version: 3.13

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.python-version }}
    - name: Install dependencies
      run: |
        cd server
        docker compose --env-file .env.test up -d
        python -m pip install --upgrade pip
        if [ -f pyproject.toml ]; then 
          pip install . ;
          pip install --group ci-pipeline
        fi
    - name: Lint with flake8
      run: |
        cd server
        find src -name "*.py" | xargs flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        find src -name "*.py" | xargs flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest

